export interface ChartmetricFilterResponse {
  cm_artist: string;
  name: string;
  pronoun?: string;
  band: boolean;
  image_url?: string;
  code2: string;
  hometown_city?: string | null;
  current_city?: string | null;
  cm_tag?: number[];
  genres?: string;
  genre_smart_ordered?: Array<Record<string, number>>;
  career_status?: {
    stage: string;
    stage_score: number;
    trend: string;
    trend_score: number;
  };
  cm_artist_rank?: number;
  rank_eg?: number;
  rank_fb?: number;
  sp_monthly_listeners?: number;
  sp_followers?: number;
  sp_popularity?: number;
  [key: string]: any; // For all the other platform stats
}

export interface ChartmetricDetailedResponse {
  obj: {
    id: number;
    name: string;
    isni?: string;
    hometown_city?: string;
    current_city?: string;
    band_members?: any;
    booking_agent?: any;
    record_label?: any;
    press_contact?: any;
    general_manager?: any;
    description?: string;
    is_custom_description?: boolean;
    is_non_artist?: boolean;
    is_duplicate?: boolean;
    hide_birthday?: number;
    hide_gender?: number;
    hide_pronoun?: number;
    hide_cover_image?: number;
    cm_artist_rank?: number;
    cm_artist_score?: number;
    rank_eg?: number;
    rank_fb?: number;
    image_url?: string;
    preview_track_id?: number;
    verified?: boolean;
    inactive?: boolean;
    associatedLabels?: any;
    genres?: any;
    topSongwriterId?: number;
    career_status?: any;
    authenticity_risk?: any;
    is_comparable?: boolean;
    mood_smart_ordered?: any[];
    activities_smart_ordered?: any[];
    genre_smart_ordered?: any[];
    moods?: any[];
    activities?: any[];
    created_at?: string;
    code2?: string;
    band?: boolean;
    pronoun_title?: string;
    gender_title?: string;
    gender?: number;
    current_city_id?: number;
    cm_artist?: number;
    cover_url?: string;
    topSongwriterCollaborators?: string[];
    artist_tier?: number;
    cm_statistics?: any;
    [key: string]: any;
  };
}

export interface MergedArtistData {
  id: number;
  name: string;
  isni?: string;
  band: boolean;
  gender?: number;
  gender_title?: string;
  pronoun_title?: string;
  code2?: string;
  hometown_city?: string;
  hometown_city_id?: number;
  current_city?: string;
  current_city_id?: number;
  image_url?: string;
  cover_url?: string;
  preview_track_id?: number;
  description?: string;
  is_custom_description?: boolean;
  career_stage?: string;
  career_stage_score?: number;
  career_trend?: string;
  career_trend_score?: number;
  artist_tier?: number;
  cm_artist_rank?: number;
  cm_artist_score?: number;
  rank_eg?: number;
  rank_fb?: number;
  sp_monthly_listeners?: number;
  sp_followers?: number;
  sp_popularity?: number;
  sp_followers_to_listeners_ratio?: number;
  ins_followers?: number;
  ins_engagement_rate?: number;
  tiktok_followers?: number;
  tiktok_likes?: number;
  tiktok_engagement_rate?: number;
  tiktok_track_posts?: number;
  ycs_subscribers?: number;
  ycs_views?: number;
  youtube_monthly_video_views?: number;
  youtube_daily_video_views?: number;
  facebook_followers?: number;
  twitter_followers?: number;
  shazam_count?: number;
  genres?: any;
  genre_smart_ordered?: any;
  moods?: any;
  mood_smart_ordered?: any;
  activities?: any;
  activities_smart_ordered?: any;
  associated_labels?: any;
  platform_stats?: any;
  platform_ranks?: any;
  weekly_diff?: any;
  monthly_diff?: any;
  bimonthly_diff?: any;
  weekly_diff_percent?: any;
  monthly_diff_percent?: any;
  playlist_stats?: any;
  where_people_listen?: any;
  verified?: boolean;
  inactive?: boolean;
  is_comparable?: boolean;
  is_duplicate?: boolean;
  is_non_artist?: boolean;
  data_timestamp?: string;
}
